### ISSUE TITLE
Tirage au sort

### ISSUE THREAD

**Issue by LeComptoirDuDev** [LeComptoirDuDev/secret-santa#2]
En tant qu'administrateur, je veux lancer un tirage au sort afin d'associer deux participants de manière aléatoire.

Deux possibilités : 
- si A offre un cadeau à B, alors B devra offrir un cadeau à A
- ou pas de règle de ce type là :)

**Comment by Syltech** [comment]
Test : s'assurer que chaque participant a offert un cadeau à un participant qui n'est pas lui même
